fix(web-conference) : add missing scss
OPEN-ENT-NG/theme-open-ent pull request #34
Opened 2022-12-05 16:10 UTC by sjollois

add missing scss for web-conference module (update from web-conference repository)

2022-12-05 16:12 UTC, qpic-cgi requested changes

2022-12-05 16:12 UTC, qpic-cgi commented on scss/specifics/web-conference/_web-conference.scss
> +    border: 1px solid lightgray;
tu ne veux pas en faire une constante de ton lightgray ?

2022-12-05 16:12 UTC, qpic-cgi approved these changes

2022-12-05 16:31 UTC, sjollois commented on scss/specifics/web-conference/_web-conference.scss
> +    border: 1px solid lightgray;
je ne fais que copier-coller ce qui existe déjà sur webconférence, je ne veux pas créer d'effet de bord indésirable ^^
Je t'invite à faire une issue sur le module web-conf :)

2022-12-06 10:42 UTC, flmartineau approved these changes

2022-12-07 08:25 UTC, merged